tags:
  - name: Product
paths:
  /product:
    get:
      tags:
        - Product
      summary: Get all products.
      responses:
        200:
          description: Responses Successful
          schema:
            $ref: '#/definitions/ResponseSuccess'
        422:
          description: Responses Validate Data
          schema:
            $ref: '#/definitions/ResponseError'
        404:
          description: Responses Data Not Found
          schema:
            $ref: '#/definitions/ResponseError'
        500:
          description: Server error
      security:
        - x-access-token: []
