definitions:
  Product:
    type: object
    properties:
      _id:
        type: string
        example: 611f764f3bd553cf780ce32a
      title:
        type: string
        example: CPU
      description:
        type: string
        example: CPU
      images:
        type: arrays
        example: [
          "users/611/avatar/2021/08/22/2ff6eaf44645c94f966fdbd582ed2886_1629638785402",
          "users/611/avatar/2021/08/22/2ff6eaf44645c94f966fdbd582ed2886_1629638785402"
        ]
      costPrice:
        type: number
        example: 1000000
      salePrice:
        type: number
        example: 1000000
      salePercent:
        type: number
        example: 10
      quantity:
        type: number
        example: 10
      specifications:
        type: arrays
        example: [
          {
            "title": "CPU",
            "content": "Intel Core i7-10700K"
          },
          {
            "title": "RAM",
            "content": "16GB"
          }
        ]
      brand:
        type: string
        example: 611f764f3bd553cf780ce32a
      category:
        type: string
        example: 611f764f3bd553cf780ce32a
      __v:
        type: integer
        example: 0
      createdAt:
        type: string
        example: 2022-10-22T09:33:51.000Z
      updatedAt:
        type: string
        example: 2022-10-22T09:33:51.000Z